"""First migration

Revision ID: 21e1e5266551
Revises: 69da0a05c301
Create Date: 2021-07-31 15:51:27.215981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e1e5266551'
down_revision = '69da0a05c301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
