"""First migration

Revision ID: 69da0a05c301
Revises: 08b7cb49b9df
Create Date: 2021-07-31 15:28:03.662135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69da0a05c301'
down_revision = '08b7cb49b9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
