"""First migration

Revision ID: a65a9df1d284
Revises: 21e1e5266551
Create Date: 2021-07-31 15:58:13.066186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65a9df1d284'
down_revision = '21e1e5266551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
